### PR TITLE
Switch to Jekyll + Grunt

### PR DESCRIPTION
**Pull request by XhmikosR**
This is a huge PR; I had started it more than 1 year ago.

Improvements:

* Everything is minified (HTML, CSS, JS)
* JS is loaded asynchronously
* Updated JS assets to latest versions
* Images are better optimized and removed duplicated and unused ones
* Sitemap and feed.xml are added
* Fixed many redirects and 404
* Fix some HTML errors, more to come

---

**Preview: http://general-manager-mark-85171.netlify.com/**

### CODE REVIEW

**Comment by XhmikosR** [comment]
@parkr: is there any way to disable kramdown's id's only for a collection? See https://ci.appveyor.com/project/FeodorFitsner/website/build/230/job/738o89pxd6938lny#L569

**Comment by parkr** [comment]
> @parkr: is there any way to disable kramdown's id's only for a collection?

No, this is a global configuration option, not available on a per-page or per-collection basis.

**Comment by XhmikosR** [comment]
So, are you aware of any way to fix the duplicate IDs in a collection? I'm
using octopress paginate here.

**Comment by parkr** [comment]
Duplicate ID's in all the documents in a collection? No. This would require
a custom solution as far as I know. I would consider it a bug, however, if
there were duplications of ids within one markdown document.

**Comment by XhmikosR** [comment]
Yeah if you check the Travis build above I'm getting hundreds of duplicate
IDs and I'm trying to solve this along with a new octopress paginate
release with those 3 fixes.

**Pull request merged**
