### PR TITLE
create amazon-elastic-beanstalk.md

### PR DESCRIPTION
**Pull request by OwenMcDonnell**

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
If it's the page about new deployment provider you should add a link to it into few places:
1. Side menu: https://github.com/appveyor/website/blob/master/src/_includes/docs_sidebar.html#L36-L53
2. Table on this page: https://github.com/appveyor/website/blob/master/src/docs/deployment/index.md

Btw, to speedup the testing of your changes locally you can use the following commands from website repo root folder:

* `grunt` - transforms website and opens it in "listening" mode in the local browser
* `grunt test` - transforms website and runs all linting checks.

**Comment by OwenMcDonnell** [comment]
I see. I wasn't aware AWS tools for VS did so.

**Comment by IlyaFinkelshteyn** [comment]
Also please specify what setting is optional. I see that S3 which we use as a template here does not have it, but let us do similar to for example https://www.appveyor.com/docs/deployment/azure-webjob/.

And in the YAMl sample please remove artifact (is single artifact is produced, AppVeyor will simple pick it), or set it to artifact deployment name, not file name. It is better practice, though both works.

**Comment by IlyaFinkelshteyn** [comment]
Artifact name is also optional. And again, in very beginning we need to explain how to  create proper artifact for EBS, maybe with YAML samples.  See https://github.com/appveyor/website/pull/446#issuecomment-379352271

**Pull request merged**
