### PR TITLE
AppVeyor Enterprise planning guide

### PR DESCRIPTION
**Pull request by FeodorFitsner**

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
@XhmikosR I'm struggling to make link checker ignoring `http://localhost` URLs. Do you know an easy way to do that?

**Comment by XhmikosR** [comment]
Judging from the link that failed you shouldn't have it as a link in the
first place:) just do it as code.

**Comment by FeodorFitsner** [comment]
Tried that but didn't work: https://github.com/appveyor/website/pull/339/commits/a47055fdd853231b357f18139e486a11db066c73

**Comment by XhmikosR** [comment]
Ok I'll have a look as soon as I have some time.

**Comment by XhmikosR** [comment]
I don't get what you have done with the branches? Is staging rebased against master?

**Comment by XhmikosR** [comment]
I can't find any way to ignore this specific error. It shouldn't happen that's for sure.

I can remove the plugin since I doubt it will be fixed even if we report it.

**Comment by FeodorFitsner** [comment]
Checking broken links is a good thing in general - no need to remove it completely. Is there any way to ignore some URLs?

**Comment by XhmikosR** [comment]
Well, we can ignore paths and ports but I can't make it work. I don't want to remove it either. This is the plugin https://github.com/ChrisWren/grunt-link-checker. If you fix it CC me so that I merge it.

For now I have removed it.

**Comment by XhmikosR** [comment]
I reverted it for #340 since you want to keep it but I can't make it exclude this specific issue.

**Pull request merged**
