### PR TITLE
Amend CodeCov upload script 

### PR DESCRIPTION
**Pull request by ceddlyburge**
This now relies on Bash and Powershell, which exist on the AppVeyor machine image and will be present on virtually all developer machines. This should make it easier to replicate the build locally, as there is no need to install python or the codedov python package.

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
Thanks for contributing that!

Could you please look at linting errors: https://ci.appveyor.com/project/AppVeyor-Website/website/build/1.0.1530#L128

**Comment by ceddlyburge** [comment]
Hi Feodor, I actually ran the linter locally and fixed everything up, but then forgot to commit it. ooops. Never mind, they're all fixed now ....

**Comment by FeodorFitsner** [comment]
Thank you!

**Comment by ceddlyburge** [comment]
No worries :)

**Pull request merged**
