### PR TITLE
docs: new sample download-artifacts.sh

### PR DESCRIPTION
**Pull request by GitMensch**
converted and extended version of download-artifacts-advanced-ps.md

after searching for that too long... here it is, script is contributed under MIT

### CODE REVIEW

**Comment by GitMensch** [comment]
Can you make that available on the GNU/Linux workers (haven't tested under MacOS yet) and for direct download please?

**Comment by GitMensch** [comment]
@FeodorFitsner Could you please review this? There were some discussions in the past about the missing non-powershell option to download artifacts, and well... here it is.

**Comment by GitMensch** [comment]
rebased and pushed without trailing spaces to fix CI check

**Comment by FeodorFitsner** [comment]
Thank you!

**Comment by GitMensch** [comment]
Can you make that script available in the images as well? That would have the benefit of not needing to create (or curl a gist version of) it each time it has to be used.

**Pull request merged**
