### PR TITLE
Add a post on integration code coverage using CodeCov

### PR DESCRIPTION
**Pull request by ceddlyburge**
As discussed, here is a blog post on integrating with CodeCov.

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
Thank you very much for the great post! It's been published: https://www.appveyor.com/blog/2017/03/17/codecov/

Btw, I noticed a broken "Code Coverage" status image under `Add Coverage Graphics to the Repository` section - is there any was to fix it?

**Comment by ceddlyburge** [comment]
Hi Feodor, I've posted an attempted fix.

I'm going to be away from technology and internet for a week now, so if
there are any other problems, I'll look at them then.

Cheers

Cedd

**Comment by FeodorFitsner** [comment]
Hi Cedd,

Looks like your last change didn't work though, but no worries, you can look into that when you are back :)

Thank you!

-Feodor Fitsner, AppVeyor


________________________________

**Comment by XhmikosR** [comment]
@FeodorFitsner: you should squash such PRs. So much noise is useless and bloats the history.

**Comment by ceddlyburge** [comment]
Hi Feodor

The image is being blocked by the img-src directive in the Content Security
Policy.

I can either add "https://codecov.io" to the img-src directive, I think via
the web.config, or I can copy the image locally.

Which would you prefer?

I also notice that frame-src directive is deprecated, and that you are
already using the suggested replacement (child-src), so I can fix that up
while I'm here if you would like?

Cheers

Cedd

**Comment by FeodorFitsner** [comment]
Hi Cedd,

I think it's better just to copy the image for now, thank you!

**Comment by ceddlyburge** [comment]
Ok, I've opened a pull request that I really definitely think should solve
the problem :)

**Comment by FeodorFitsner** [comment]
Looks great, thanks!

**Comment by ceddlyburge** [comment]
Phew! Didn't have to eat my words :)

**Pull request merged**
