### PR TITLE
Add anchor.js for docs

### PR DESCRIPTION
**Pull request by XhmikosR**
@FeodorFitsner: this is a first draft. The CSS will need some tweaking.

So, please don't merge it yet, just test it locally and let me know your thoughts.

### CODE REVIEW

**Comment by XhmikosR** [comment]
You shouldn't merge it yet... I wanted to move the anchor after the text
and not before. Also I wanted to tweak the breakpoint to hide it.

**Comment by XhmikosR** [comment]
What was the URL the staging branch goes live? We need this documented BTW.

**Comment by FeodorFitsner** [comment]
But it looks nice already, imho! :)

I also added scrolling to anchor with a fixed header and fixed auto-anchor to apply to H2 and above inside document article only. You can see how it works on this page: http://appveyor-staging.azurewebsites.net/docs/build-configuration

**Comment by XhmikosR** [comment]
Yeah I planned to do this too. I will check your solution when I'm back and
make a PR if needed.

**Comment by FeodorFitsner** [comment]
Sure. Anchor on the left is definitely better! Let's leave it there.

Anyway, looks cool - thank you!

**Comment by XhmikosR** [comment]
I definitely don't like your solution so I'll make a proper PR later. Also
you shouldn't touch the 3rd party files like anchor.js....

**Comment by FeodorFitsner** [comment]
Sure, will check it out.

**Pull request merged**
