### PR TITLE
Assorted updates

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @FeodorFitsner

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
You are merging `xmr` branch to `master` here, not `staging`? I'm a little confused by the purpose of this "Merge staging to master" PR.

**Comment by XhmikosR** [comment]
You do see the commits, don't you?

**Comment by FeodorFitsner** [comment]
What do you mean?

**Comment by XhmikosR** [comment]
I don't understand your original question then. These patches were in the staging branch which then you decided you want to use for other things.

Anyway, either merge or close.

**Comment by FeodorFitsner** [comment]
Got it. So, it's improvements for master branch, right?

**Comment by XhmikosR** [comment]
Yup. I also had another patch but removed it since it caused issues with the selectors we currently override for Foundation. I might give it another go in the future when I have some time.

**Pull request merged**
