### PR TITLE
Refactor images.

### PR DESCRIPTION
**Pull request by XhmikosR**
Might need a rebase after #31 is merged.

### CODE REVIEW

**Comment by XhmikosR** [comment]
This can be merged too. From the next PR I will use the staging branch. You should add a README with some guidelines though.

**Comment by FeodorFitsner** [comment]
This PR breaks left sidebar and topbar again.

**Comment by XhmikosR** [comment]
Well, isn't that normal since you test without this merged?

**Comment by XhmikosR** [comment]
Rebased, but please try to bear with me, don't make me rebase 1000 times a day ;)

**Comment by FeodorFitsner** [comment]
Looks good now, merging.

**Comment by FeodorFitsner** [comment]
This is called "teamwork" :) Sorry for all that hassle, I've used to work alone on that stuff. But I love your work, especially this PR putting images into right place! Thank you for your time and efforts!

I'm making staging branch now.

**Comment by XhmikosR** [comment]
All right, cool. I finished the IE images fix.

I'm telling you, IE is a decease... Let's hope with Windows 10 Microsoft will finally move to a Webkit based browser.

**Comment by FeodorFitsner** [comment]
Yes, IE is bad. Read somewhere it's not going to be WebKit in IE vNext, but still their own engine :-E

**Comment by XhmikosR** [comment]
They never learn, do they :p

**Comment by FeodorFitsner** [comment]
Yeah :)

**Pull request merged**
