### PR TITLE
branches.md: fix or improve regexes

### PR DESCRIPTION
**Pull request by dtikhonov**

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
Agree with version regexp, but for `/dev-.*/` there was an idea to ignore all branches starting from `dev-`, like `dev-p1`, `dev-feature-A`, etc.

**Comment by dtikhonov** [comment]
OK, my point was that `.*` means "zero or more of anything", so if nothing follows it, it can be omitted.

As for "begins with" I was going to suggest using an anchor (e.g. `/^dev-/`), but I don't know what is being compared against.  For example, `/^dev-/` would not match `origin/dev-123`

**Comment by FeodorFitsner** [comment]
Would it make sense to replace it with `/dev-.+/` then?

**Comment by dtikhonov** [comment]
If you want to exclude branches named "dev-", yes.  (Even though `/dev-.+/` is equivalent to `/dev-.`, for the former may be easier to read for majority of people.)

**Pull request merged**
