### PR TITLE
Creating a Signed and ZipAligned APK (for Google Play) from Xamarin

### PR DESCRIPTION
**Pull request by ceddlyburge**
Hi There

I have been exploring AppVeyor on a hobby project recently, and emailed Ilya Finkelshteyn to see whether a blog post on the subject would be welcome.

He sounded keen, so here it is!

I hope you like it.

Cheers

### CODE REVIEW

**Comment by IlyaFinkelshteyn** [comment]
Thanks a lot! Could you please fix build issues when you have a chance? They are small markdown errors from https://ci.appveyor.com/project/AppVeyor-Website/website/build/1.0.701#L155 to https://ci.appveyor.com/project/AppVeyor-Website/website/build/1.0.701#L164...

**Comment by ceddlyburge** [comment]
Hi Ilya, I've fixed up all those linter issues.

Cheers

Cedd

**Comment by FeodorFitsner** [comment]
Thank you for amazing post!

It's been published to a live site: https://www.appveyor.com/blog/2016/11/22/create-signed-aligned-xamarin-apk/

**Comment by ceddlyburge** [comment]
Thanks Feodor!

**Pull request merged**
