### PR TITLE
Updated ToS, EULA and privacy policy

### PR DESCRIPTION
**Pull request by FeodorFitsner**
@XhmikosR can you tell me please why HTML check is complaining there: https://ci.appveyor.com/project/appveyor-website/website/build/1.0.941#L635?

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
@XhmikosR can you tell me please why HTML check is complaining there: https://ci.appveyor.com/project/appveyor-website/website/build/1.0.941#L635?

**Comment by XhmikosR** [comment]
You have probably left a tag unclosed somewhere...

**Comment by FeodorFitsner** [comment]
I guess so, but for some reason the checker doesn't say where exactly... May be you can spot the issue?

**Comment by XhmikosR** [comment]
@FeodorFitsner: please check now. I tried to be as consistent as possible and fix any formatting issues too.

**Comment by FeodorFitsner** [comment]
Wow, thanks! What tool did you use to find the issue?

**Comment by XhmikosR** [comment]
The validator in dev mode. When testing the validator runs after it has build everything from production hence why the not so meaningful output.

**Comment by FeodorFitsner** [comment]
what command is that?

**Comment by XhmikosR** [comment]
`grunt dev` and in another window while that is running `grunt htmllint`.

**Comment by FeodorFitsner** [comment]
Good to know, thanks.

**Pull request merged**
