### PR TITLE
Merge staging to master

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @FeodorFitsner

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
I don't want to merge it right now, but keep AppVeyor Enterprise work going in `staging` branch for a while.

**Comment by XhmikosR** [comment]
You should have made another branch... Please push the `enterprise-planning` to another branch based on master and not staging.

**Comment by FeodorFitsner** [comment]
But I want to publish to staging site and collaborate with others until it's ready.

**Comment by XhmikosR** [comment]
Yes, but I don't have access to all branches. And this makes it hard for me to contribute anything in the future.

For now see #341 but I won't do the same again.

**Pull request closed without merging**
