### PR TITLE
Add Python language chapter to docs

### PR DESCRIPTION
**Pull request by bittner**
This adds a new chapter to the documentation, which explains concisely how to setup up (best practice) testing automation on AppVeyor for projects using the Python programming language.

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
Hi Peter, thanks for contributing that!

Is it ready for publishing?

**Comment by bittner** [comment]
Sure! Go for it! :+1:

**Comment by FeodorFitsner** [comment]
Cool, thanks!

**Comment by bittner** [comment]
Thanks for merging! And, yay, it's [already online](https://www.appveyor.com/docs/lang/python/), great!

**Pull request merged**
