### PR TITLE
windows-images-software.md: Revert VS 16.4 Preview 1

### PR DESCRIPTION
**Pull request by SergeGautherie**
Not yet deployed.

Addendum to 8c5644591b2e53a4a802573006962c71bf9bdd09.

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
Why? `Visual Studio 2019 Preview` image has been updated some time ago: https://github.com/appveyor/ci/issues/3111

**Comment by SergeGautherie** [comment]
Hum: was it?

VS2019:
```
msbuild -version
Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
16.3.0.46305
```

VS2019P:
```
msbuild -version
Microsoft (R) Build Engine version 16.3.0-preview-19456-02+ee8294b55 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
16.3.0.45602
```

**Comment by FeodorFitsner** [comment]
Yep, I've RDPed into VM with VS 2019 Preview and took a screenshot:

image

MSBuild version corresponds to yours, but it's VS 2019 16.4 P1 in About window.

**Comment by SergeGautherie** [comment]
Hum, I agree the IDE was updated, so this PR is wrong.

---

Nonetheless, the VS2019P image is not a "VS2019 + a few previews" that I would expect:
```
VS2019 : (Hyper-V), WS2019 (10.0.17763), .Net Framework 4.8.03761, ...
VS2019P: (Google) , WS2016 (10.0.14393), .Net Framework 4.7.03062, ...
```
Is that intended?

--

For what it's worth, it seems VS2019 msbuild was upgraded to 16.3.1.50202 today, when the image was moved to Hyper-V, though no update was announced.
Was that intended? Or is it a clue that something is going "wrong" with the (previous) installations?

**Comment by FeodorFitsner** [comment]
Right, while moving to Hyper-V VS 2019 was upgraded to 16.3.3. Announcement will follow, thanks for the catch - we are still watching this new Hyper-V image before deciding on final move.

...it's like we were building the images simultaneously on Azure and Hyper-V and VS 2019 16.3.3 was released during the process, so Azure was ended with 16.3.2 and Hyper-V with 16.3.3 :)

**Pull request closed without merging**
