### PR TITLE
Whitespace normalization.

### PR DESCRIPTION
**Pull request by XhmikosR**
PS: @FeodorFitsner: how can we specify the language to use for code highlighting? In Jekyll I would do

```
{% highlight yaml %}
foo
{% endhighlight %}
```

### CODE REVIEW

**Comment by XhmikosR** [comment]
@FeodorFitsner: any thoughts for my PRs?

**Comment by FeodorFitsner** [comment]
Sure, will take a look. Sorry for the delay. Lot's of support today :)

**Comment by XhmikosR** [comment]
How about syntax highlighting? Is it supported currently? If not I guess we can go with a JS solution which should be easy to add.

**Comment by FeodorFitsner** [comment]
That code highlighting tag was kinda experimental (and depending on web service) and it's not currently used. Also, there is a problem with it working together with markdown. We have to find decent highlighting library.

**Comment by XhmikosR** [comment]
Well, for client side there are many. I can make a branch tomorrow or so for that if you want.

**Comment by FeodorFitsner** [comment]
Sure, give it a try.


-Feodor

**Comment by XhmikosR** [comment]
All right, I hope we can merge some stuff until then so that I don't have to rebase all the time.

**Pull request merged**
