### PR TITLE
Merge staging to master.

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @FeodorFitsner

### CODE REVIEW

**Comment by XhmikosR** [comment]
@FeodorFitsner: do not merge yet. I'm trying to solve an error with happens with the current live site and IE 10.

**Comment by XhmikosR** [comment]
@FeodorFitsner: I can't figure out why IE9 and 10 are broken, in master too.

So I cleaned this branch up, please merge and I'll try to find the cause later.

**Comment by XhmikosR** [comment]
Should we even care about IE < 11 @FeodorFitsner?

**Comment by FeodorFitsner** [comment]
I don't think so. Where would you find IE 10 these days?

**Comment by XhmikosR** [comment]
OK, so we are fine. IE 11 works fine in my tests.

**Comment by FeodorFitsner** [comment]
Cool!

**Pull request merged**
