### PR TITLE
Add code highlighting

### PR DESCRIPTION
**Pull request by XhmikosR**
@FeodorFitsner: it seems only PrismJS supports YAML and not completely official; I had to use a language plugin.

Don't merge this yet, just test it and let me know your thoughts.

PS. I might switch to https://code.google.com/p/google-code-prettify/ which seems to support YAML.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@FeodorFitsner: we need to update the NJekyll code to not try to replace tags like in the case of `<pre>` because now we get

```
subject: 'Build '                  # optional
```
instead of
```
subject: 'Build {{status}}'                  # optional
```

**Comment by XhmikosR** [comment]
@FeodorFitsner: so what should I do with this?

**Comment by FeodorFitsner** [comment]
Honestly, I don't think we are in a great need of code highlighting. Most examples on website are YAML. Besides, I noticed there are some issues with formatting in Markdown lib when converting .MD with highlighted code blocks.

What would be really interesting to implement though is this: http://ben.balter.com/2014/03/13/pages-anchor-links/

**Comment by XhmikosR** [comment]
I'd rather use [anchor.js](https://github.com/bryanbraun/anchorjs) since we don't care about IE < 9, but that it's a separate issue and easy to add anyway. I can have a look at it soon.

Personally, I strongly believe we should have code highlighting. Can't you sort the C# code so that we don't hit these issues like the one I mention?

**Comment by XhmikosR** [comment]
BTW, can you bring staging on par with master?

**Comment by 304NotModified** [comment]
:heart:  code highlighting

**Pull request closed without merging**
